export const DEFAULT = 'DEFAULT';

// songs
export const GET_SONG_LIST_REQUEST = 'GET_SONG_LIST_REQUEST';
export const GET_SONG_LIST_SUCCESS = 'GET_SONG_LIST_SUCCESS';
export const GET_SONG_LIST_ERROR = 'GET_SONG_LIST_ERROR';

// song
export const GET_SONG_REQUEST = 'GET_SONG_REQUEST';
export const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
export const GET_SONG_ERROR = 'GET_SONG_ERROR';

// collections
export const GET_COLLECTIONS_LIST_REQUEST = 'GET_COLLECTIONS_LIST_REQUEST';
export const GET_COLLECTIONS_LIST_SUCCESS = 'GET_COLLECTIONS_LIST_SUCCESS';
export const GET_COLLECTIONS_LIST_ERROR = 'GET_COLLECTIONS_LIST_ERROR';

// letters
export const GET_LETTERS_REQUEST = 'GET_LETTERS_REQUEST';
export const GET_LETTERS_SUCCESS = 'GET_LETTERS_SUCCESS';
export const GET_LETTERS_ERROR = 'GET_LETTERS_ERROR';

// font size
export const INCREASE_FONT_SIZE = 'INCREASE_FONT_SIZE';
export const DECREASE_FONT_SIZE = 'DECREASE_FONT_SIZE';
