export const DEFAULT = 'DEFAULT';

// songs
export const GET_LIST_SONGS_REQUEST = 'GET_LIST_SONGS_REQUEST';
export const GET_LIST_SONGS_SUCCESS = 'GET_LIST_SONGS_SUCCESS';
export const GET_LIST_SONGS_ERROR = 'GET_LIST_SONGS_ERROR';

// song
export const GET_SONG_REQUEST = 'GET_SONG_REQUEST';
export const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
export const GET_SONG_ERROR = 'GET_SONG_ERROR';

